SocketDev/socket-python-cli

- socketsecurity/socketcli.py
There is a bug in the script that causes a comment to be posted even if there are no new/removed packages in a diff.
> Fix removed_packages length check

- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
- socketsecurity/core/classes.py
- socketsecurity/core/messages.py
- socketsecurity/socketcli.py
- Adds support for Security Policy Modes Block & Warn
**Note:**  The Python CLI does not currently support individually triaged alerts
- Comments have been updated to have a new column in Github and Gitlab Comments with the new version to indicate Block/Warn
- The console output will include the CI Status of Block/Warn as well
- New option `--ignore-commit-files` to look for all manifest files whether or not there is one in the last commit detected
- Updated docker containers of `socketdev/cli:1.0.0` and `socketdev/cli:latest` have been pushed
> Added support for Warn & Monitor policy modes

- socketsecurity/core/__init__.py
TLS was always disabled because verify was swapped around and always defaulting to false.
> Fixed verify bool being swapped

- .gitignore
- pyproject.toml
- requirements.txt
- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
- socketsecurity/core/github.py
- socketsecurity/socketcli.py
- Migrated all the direct calls to the API to instead use the python SDK
- Slight refactor of the Core class to explicitly make it a static class instead of mixing static and instance variables / state
- Added the dev dependency Ruff, a modern, more performant language server and linter
- Added python-dotenv and some config for setting up a .env.local file for setting env vars
I've attempted to thoroughly test these changes, but given how new I am to the codebase and company, I'd love a sanity check
> migrate from direct API usage to SDK

- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
The API can handle case-insensitivity but we were previously not matching that in the CLI
> manifest file search now case-insensitive

- .github/workflows/docker-stable.yml
- .github/workflows/pr-preview.yml
- .github/workflows/release.yml
- scripts/build_container.sh
After a bit of digging, it turns out that we do need to specify the platforms so that arm64 hosts (like apple silicon macbooks) can run the resulting docker image. So instead of removing the platforms, I added the requisite workflow steps to get buildx set up.
> Updated workflows for buildx support

- .github/workflows/release.yml
We were missing the CLI_VERSION build-arg in the release workflow's docker build step.
I didn't increment the version number to indicate that nothing in the CLI itself changed
> added CLI_VERSION build-arg to build docker step

- socketsecurity/__init__.py
- socketsecurity/core/messages.py
Added link to socket.dev for package alert.
> Improved file line number glob. 

- pyproject.toml
- socketsecurity/__init__.py
Pyproject specified too high of a minimum python version (3.11)
This was originally driven by the sdk's typing improvements, and when the sdk used a polyfill library to lower this requirement, the change wasn't made in the CLI.
> lowered required python version to 3.9

- README.md
- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/config.py
- socketsecurity/core/__init__.py
- socketsecurity/core/messages.py
- socketsecurity/core/socket_config.py
- socketsecurity/output.py
- socketsecurity/socketcli.py
Didn't incorporate ALL the SARIF changes in v2.
> added SARIF back in

- .gitignore
- Pipfile.lock
- README.md
- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/config.py
- socketsecurity/core/__init__.py
- socketsecurity/core/classes.py
- socketsecurity/core/scm/github.py
- socketsecurity/core/utils.py
- socketsecurity/socketcli.py
Click on the "Preview" tab and select appropriate PR template:
[New Feature](?expand=1&template=feature.md)
[Bug Fix](?expand=1&template=bug-fix.md)
[Improvement](?expand=1&template=improvement.md)
> Fixes for diff logic

- README.md
- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
- Our file search (`Core#find_files`) was adding directories as well as files to the processing list
- Our README didn't fully document the behavior and use cases for the --files and --ignore-commit-files args
> updated file behavior docs and skipping dirs in file search

- socketsecurity/__init__.py
- socketsecurity/core/messages.py
Click on the "Preview" tab and select appropriate PR template:
[New Feature](?expand=1&template=feature.md)
[Bug Fix](?expand=1&template=bug-fix.md)
[Improvement](?expand=1&template=improvement.md)
> Fixed a bug with alert in multiple files

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
> Now using supported files SDK endpoint for file globs

- socketsecurity/__init__.py
- socketsecurity/core/socket_config.py
In the refactor of the code the BASE_API_URL for local testing. 
Added back in the option to override this via an environment variable. 
N/A
> Added back BASE_API_URL for the Socket API base

- .github/workflows/pr-preview.yml
- .github/workflows/release.yml
- .hooks/sync_version.py
- .hooks/sync_versions.py
- .pre-commit-config.yaml
- Pipfile.lock
- docs/README.md
- pyproject.toml
- requirements-dev.lock
- requirements.lock
- socketsecurity/__init__.py
- socketsecurity/socketcli.py
API URL could not be overridden correctly
API Url could be set via an Environment variable but it wasn't being passed to the underlying SDK
Passed the captured override to the SDK
N/A
> Fixed the ability to override the API URL for Socket Requests

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
- socketsecurity/core/classes.py
Issue with creating a new repo and handling there being no full scan causing an error. Also, when there was no head full scan there were no results.
When switching to the new endpoint some of the logic for when not diffing were removed which caused a gap in detection.
1. When creating a repo because it doesn't exist yet in the retry adding in logic to handle the no head scan
2. removed a hardcoded variable that was forcing diff and then bypassing diff when no head full scan
3. Added the logic back in for treating the results from the full scan as the diffed results
4. Fixed the package creation from SBOM Artifact to include purl and package url
- Fixed CLI logic to correctly handle when there is no head full scan or the repo does not exist before the full scan is ran
> Bumped version for release

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
CLI could have a failure if the Full Scan was empty
get_sbom_data would try to reference response.artifacts which didn't exist if the full scan was empty
Added a check for the class attribute and if not present just return the empty result
- Fixed an issue that could lead to the Python CLI failing if the full scan had no results
> Updated version for build

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/config.py
- socketsecurity/core/__init__.py
When no top level ancestors the cli would fail
assuming an attribute existed when it did not or was none
Added a check for the attribute
- Fix for a case where an attribute of a package could be None and cause the cli to fail
> Updated version

- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
SDK was stripping some attributes that was causing issues for the CLI
When the client side de duping logic was added to the SDK it was accidentally stripping attributes. This caused some needed ones to not make it to the CLI.
Updated the project definition to use the latest version of the SDK that is fixed.
- Updated Python CLI to use the Socket SDK Python 2.0.21 to fix issues with missing attributes in results
> bumped version

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
Windows paths are no longer being normalized correctly
In the 2.0 refactor the logic to normalize was lost
Add normalizing logic back to the code
N/A
> Fix Windows Path Normalization

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/plugins/slack.py
in <module>
from config import CliConfig
ModuleNotFoundError: No module named 'config'
Relative path import works locally but not when deployed
Corrected to have a full path versus relative
N/A
> Fixed slack import breaking bug

- README.md
- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/config.py
- socketsecurity/core/__init__.py
- socketsecurity/core/socket_config.py
- socketsecurity/socketcli.py
Adding support to exclude ecosystems from scanning
For customers where certain language results aren't desired it is not possible to disable ecosystems
- Added support to exclude Ecosystems from the Socket CLI Scans based on the Supported Files API Endpoint
> Added support for exlcuded ecosystems

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/core/__init__.py
- socketsecurity/core/classes.py
- socketsecurity/socketcli.py
Python CLI was erroring out on generating license from both using the new diff endpoint and the license objects changing.
Added in logic to use the batch purl endpoint to retrieve the license details.
- Fixed the CLI to work with generating the license attribution again. The `license_text` property has been replaced with `licenseDetails` and `licenseAttrib`
> Fixed license generation using the purl endpoint

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/core/scm/github.py
Right now the EVENT_ACTION has to be set in the Github Workflow. Trying to simplify things and require less hard coding of variables for the end user.
If the custom variable wasn't set then the EVENT_ACTION was None
- Update the Github logic to read the event action from the GITHUB_EVENT_PATH payload file if EVENT_ACTION is not set.
N/A
> Automatically detect GitHub event action from event payload if not set in workflow

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/core/git_interface.py
- Add _is_merge_commit() method to detect merge commits
- Add _detect_merge_commit_changes() method for merge commit file detection
- Use git diff with parent commit for merge commits instead of git show
- Fallback to git show if merge detection fails
- Maintains existing functionality for non-merge commits
Tested on GitHub actions. Prior to these updates, it showed no manifest file changes for merge commits and conducted a full scan. Now it picks up on the parent commit and manifest files.
> feat: add minimal merge commit detection support

- pyproject.toml
- socketsecurity/__init__.py
- socketsecurity/output.py
- socketsecurity/plugins/slack.py
Added comprehensive Slack webhook debugging functionality to the `--enable-debug` parameter. This improvement enhances troubleshooting capabilities for Slack webhook configuration by always displaying debug information when debug mode is enabled, regardless of whether there are security alerts or if Slack is enabled/disabled.
- **Enhanced OutputHandler**: Added Slack webhook debugging that runs whenever `--enable-debug` is used
- **Improved SlackPlugin**: Added additional debug logging for webhook execution status
- **Always-on debugging**: Moved Slack debug output outside the plugin-enabled conditional so it shows configuration status even when Slack is disabled
- **Comprehensive information display**: Shows environment variables (`SOCKET_SLACK_ENABLED`, `SOCKET_SLACK_CONFIG_JSON`), …
> chore: add slack debugging
